export const movieCards = [
  {
    id: `1`,
    img: `img/fantastic-beasts-the-crimes-of-grindelwald.jpg`,
    title: `Fantastic Beasts: The Crimes of Grindelwald`,
    href: `movie-page.html`,
  },
  {
    id: `2`,
    img: `img/bohemian-rhapsody.jpg`,
    title: `Bohemian Rhapsody`,
    href: `movie-page.html`,
  },
  {
    id: `3`,
    img: `img/macbeth.jpg`,
    title: `Macbeth`,
    href: `movie-page.html`,
  },
  {
    id: `4`,
    img: `img/aviator.jpg`,
    title: `Aviator`,
    href: `movie-page.html`,
  },
  {
    id: `5`,
    img: `img/we-need-to-talk-about-kevin.jpg`,
    title: `We need to talk about Kevin`,
    href: `movie-page.html`,
  },
  {
    id: `6`,
    img: `img/what-we-do-in-the-shadows.jpg`,
    title: `What We Do in the Shadows`,
    href: `movie-page.html`,
  },
  {
    id: `7`,
    img: `img/revenant.jpg`,
    title: `Revenant`,
    href: `movie-page.html`,
  },
  {
    id: `8`,
    img: `img/johnny-english.jpg`,
    title: `Johnny English`,
    href: `movie-page.html`,
  },
  {
    id: `9`,
    img: `img/shutter-island.jpg`,
    title: `Shutter Island`,
    href: `movie-page.html`,
  },
  {
    id: `10`,
    img: `img/pulp-fiction.jpg`,
    title: `Pulp Fiction`,
    href: `movie-page.html`,
  },
  {
    id: `11`,
    img: `img/no-country-for-old-men.jpg`,
    title: `No Country for Old Men`,
    href: `movie-page.html`,
  },
  {
    id: `12`,
    img: `img/snatch.jpg`,
    title: `Snatch`,
    href: `movie-page.html`,
  },
  {
    id: `13`,
    img: `img/moonrise-kingdom.jpg`,
    title: `Moonrise Kingdom`,
    href: `movie-page.html`,
  },
  {
    id: `14`,
    img: `img/seven-years-in-tibet.jpg`,
    title: `Seven Years in Tibet`,
    href: `movie-page.html`,
  },
  {
    id: `15`,
    img: `img/midnight-special.jpg`,
    title: `Midnight Special`,
    href: `movie-page.html`,
  },
  {
    id: `16`,
    img: `img/war-of-the-worlds.jpg`,
    title: `War of the Worlds`,
    href: `movie-page.html`,
  },
  {
    id: `17`,
    img: `img/dardjeeling-limited.jpg`,
    title: `Dardjeeling Limited`,
    href: `movie-page.html`,
  },
  {
    id: `18`,
    img: `img/orlando.jpg`,
    title: `Orlando`,
    href: `movie-page.html`,
  },
  {
    id: `19`,
    img: `img/mindhunter.jpg`,
    title: `Mindhunter`,
    href: `movie-page.html`,
  },
  {
    id: `20`,
    img: `img/midnight-special.jpg`,
    title: `Midnight Special`,
    href: `movie-page.html`,
  },
];

